dart-lang/web

- analysis_options.yaml
- lib/src/dom/angle_instanced_arrays.dart
- lib/src/dom/console.dart
- lib/src/dom/cssom.dart
- lib/src/dom/ext_disjoint_timer_query.dart
- lib/src/dom/ext_disjoint_timer_query_webgl2.dart
- lib/src/dom/oes_draw_buffers_indexed.dart
- lib/src/dom/oes_vertex_array_object.dart
- lib/src/dom/ovr_multiview2.dart
- lib/src/dom/testutils.dart
- lib/src/dom/wasm_js_api.dart
- lib/src/dom/webgl_compressed_texture_astc.dart
- lib/src/dom/webgl_debug_shaders.dart
- lib/src/dom/webgl_draw_buffers.dart
- lib/src/dom/webgl_draw_instanced_base_vertex_base_instance.dart
- lib/src/dom/webgl_lose_context.dart
- lib/src/dom/webgl_multi_draw.dart
- lib/src/dom/webgl_multi_draw_instanced_base_vertex_base_instance.dart
- lib/src/dom/webgl_provoking_vertex.dart
- lib/src/dom/webgpu.dart
- tool/bindings_generator/generate_bindings.dart
- tool/bindings_generator/translator.dart
- tool/bindings_generator/util.dart
Avoids making types private
Remove associated ignores from analysis options
> Use $prefix for namespaces, mark them abstract, fix naming of extensions

- tool/bindings_generator/generate_bindings.dart
- tool/bindings_generator/translator.dart
- tool/bindings_generator/util.dart
This adapts the generator to work with latest Dart SDK. Recently the SDK removed `JSNumber.toDart`. I could have replaced the calls with `.toDartInt`, but instead, I switched the `JSArray.length` to specify an `int` return value. In the process I also updated the indexing operator to accept `int` values, and remove the need to explicitly convert indices to a JSNumber as well.
> Update JSArray extension to use `int` types.

- .github/workflows/test-package.yml
- CHANGELOG.md
- lib/helpers.dart
- lib/src/helpers/events/providers.dart
- pubspec.yaml
- test/helpers_test.dart
Closes https://github.com/dart-lang/web/issues/77
typeofEquals now takes a String and returns a bool, and instanceOfString is the canonical replacement for isInstanceOfDomType. Removes now unneeded test as well. Updates min SDK version.
> Refactor typeofEquals usage and remove isInstanceOfDomType

- tool/bindings_generator/translator.dart
- tool/bindings_generator/util.dart
- tool/bindings_generator/webidl_api.dart
All of these go through .toDart conversions anyways, so we should just use the Dart primitive instead of the JS type primitive on these members.
> Remove unnecessary JS types from webidl_api

- CHANGELOG.md
- lib/helpers.dart
In trying to migrate from `dart:html` to `package:web`, it was not obvious to me how to create an iFrame element. Not sure if you think this is special enough to special case with its own helper, but thought I'd push up a PR to propose.
@srujzs
> Add `createIFrameElement` helper

- CHANGELOG.md
- analysis_options.yaml
- lib/src/helpers/events/events.dart
- pubspec.yaml
Cleanup SDK constraint now that Dart 3.2 is stable
> Add event extensions for `WebSocket`

- .github/dependabot.yml
- .github/workflows/build.yml
- .github/workflows/post_summaries.yaml
- .github/workflows/publish.yaml
- README.md
- update the CI workflow to test the generation script
- fix https://github.com/dart-lang/web/issues/30
- update the publishing automation setup to support PRs from forks
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change).
- Changes to packages …
> update the CI workflow to test the generation script

- CHANGELOG.md
- README.md
- bindings_generator/generate_bindings.dart
- bindings_generator/package-lock.json
- bindings_generator/package.json
- lib/src/dom/cssom.dart
- tool/update_bindings.dart
- write additional version info into the readme (include the version info for `@webref/css` as well)
- update the css idl from `6.8.1` to `6.10.0`
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change).
- Changes to packages require [corresponding …
> write additional version info into the readme

- CHANGELOG.md
- pubspec.yaml
- rev to 0.4.1 in preparation for publishing
From the changelog, the only deprecation that users are likely to see is "Deprecated the `helpers.dart` library in favor of `web.dart`". If we wanted to reduce the impact of this version on people's CIs, we could un-deprecate `helpers.dart`, continue to prefer importing `web.dart` in docs and such - and wait until a future 0.5.0 release to deprecate the helpers.dart import.
---
<details>
- Contributions to our repos should follow the [Dart style …
> rev to 0.4.1 in preparation for publishing

- CHANGELOG.md
- lib/helpers.dart
- lib/src/helpers/extensions.dart
- pubspec.yaml
These deprecations are breaking for Flutter CI. Let's do them in a breaking change version instead.
> Undeprecate some APIs and prepare for publish of 0.4.2

- CHANGELOG.md
- lib/helpers.dart
- lib/src/helpers/extensions.dart
- pubspec.yaml
Moves us to `0.5.0-wip` as well.
> Redeprecate deprecated APIs in 0.4.1

- analysis_options.yaml
- lib/fix_data.yaml
- test/dart_fix_test.dart
- test/scrape_mdn_test.dart
- test_fixes/renames.dart
- test_fixes/renames.dart.expect
- tool/renames.md
- improve testing of the 'dart fix' data
- remove fix data references to previous package:web types we no longer generate
When we reduced the number of generated APIs we stopped generating some classes referenced in the `lib/fix_data.yaml` file. Our testing didn't catch this, since the running `dart fix --compare-to-golden` just mechanically confirms that it can transform the file, not whether the resulting file is error free.
This PR creates a new temporary project with the `test_fixes/renames.dart` file - which contains the older dart:html type names - runs `dart fix` on that project, to update the references to the new package:web names, and runs `dart analyze` to make sure the result has no analysis issues.
---
<details>
- See our …
> improve testing of the 'dart fix' data

- README.md
- tool/generator/bcd.dart
This makes it easier for users to determine why some APIs are emitted the way they are.
> Add info on generation conventions

- .github/workflows/build.yml
- CHANGELOG.md
- lib/src/dom.dart
- lib/src/dom/html.dart
- lib/src/dom/trusted_types.dart
- pubspec.yaml
- tool/generator/translator.dart
Fixes https://github.com/dart-lang/web/issues/172
> Add TrustedTypes

- README.md
- third_party/mdn/README.md
- tool/README.md
- tool/update_bindings.dart
etc to tool directory,Offers very little benefit for almost all users
> Move IDL version details

- tool/update_bindings.dart
When analyzing library elements, we should use their import URIs instead of their library name. This is especially relevant as https://dart-review.googlesource.com/c/sdk/+/352977 is planning to remove the library name from dart:js_interop.
Also fixes an issue where we were returning instead of continuing in the loop that iterates over dart:js_interop and cleans up references to dart:_js_types which aren't needed anymore.
> Use URI instead of library name

- README.md
- tool/README.md
- tool/update_bindings.dart
- update the format of the web idl versions file
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change).
Note that many Dart …
> update the format of the web idl versions file

- README.md
- tool/README.md
- add instructions for re-generating the package
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change).
Note that many Dart …
> add instructions for re-generating the package

- tool/update_bindings.dart
ExternalDartReference has been added to dart:js_interop but is not a JS type and doesn't belong in the type hierarchy for union calculation. Fixes an assertion failure.
> Only consider extension types that start with JS as JS types

- .github/workflows/build.yml
- CHANGELOG.md
- pubspec.yaml
Allows us to use the latest pkg:test
> Require Dart 3.4

- tool/generator/type_aliases.dart
This is a new typed array in the w3 spec. Since we don't have a specific type for this, we alias it to JSTypedArray.
> Add Float16Array alias

- CHANGELOG.md
- lib/src/dom/webgl1.dart
- lib/src/dom/webgl2.dart
- tool/generator/translator.dart
_desugarTypedef accepts a _RawType and returns its underlying type if it's a typedef. However, it doesn't account for whether the _RawType is nullable or not. In order to accurately desugar a use of a typedef, we should union the _RawType's nullability with the underlying type's nullability. For example, `SomeTypedef?` should always be nullable after being desugared.
> Account for typedef nullability

- tool/generator/translator.dart
Web IDL allows members to have the same name as their return or parameter types. Dart does not, and therefore, we have to rename them. Cleans up some existing code and makes renaming consistent by always adding an underscore if needed.
> Rename members when they collide with return/parameter type names

- lib/src/helpers/enums.dart
This PR adds the missing declaration of `MAC_FF_META` key code value to the `KeyCode` constants.
`MAC_Fleur_META` (value is 224)  is fired by Firefox on macOS when pressing the META key, instead of the common META key value (91).
I kept the same comment as Closure's Keycode enumeration.
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package …
> Add MAC_FF_META to KeyCode constants

- lib/src/dom/css_typed_om.dart
- lib/src/dom/dom.dart
- lib/src/dom/fetch.dart
- lib/src/dom/geometry.dart
- lib/src/dom/html.dart
- lib/src/dom/indexeddb.dart
- lib/src/dom/media_source.dart
- lib/src/dom/mediastream_recording.dart
- lib/src/dom/notifications.dart
- lib/src/dom/performance_timeline.dart
- lib/src/dom/push_api.dart
- lib/src/dom/url.dart
- lib/src/dom/webauthn.dart
- lib/src/dom/webcodecs.dart
- lib/src/dom/webrtc.dart
- tool/generator/doc_provider.dart
- tool/generator/translator.dart
Static MDN members are suffixed with `_static`. Like with compatibility data, we should add this suffix when emitting docs.
> Account for static members in MDN docs

- tool/generator/translator.dart
The latter was separated from the former to avoid conflation (see https://github.com/dart-lang/sdk/issues/49025). Makes CI green again.
> Relabel unused_element ignore to unused_element_parameter

- CHANGELOG.md
- lib/src/helpers.dart
- lib/src/helpers/extensions.dart
- lib/src/helpers/lists.dart
- test/helpers_test.dart
[feat] Adds a helpers to convert js list to a dart list  (Resolves #281)
Updates:
* Converted `TouchListWrapper` to `JSListWrapper` which is a generic wrapper  to work with different types of js list.
* Updates `TouchListConvert` to use `JSListWrapper`.
* Added two new helpers, `HTMLCollectionConvert` on `HTMLCollection` and `NodeListConvert` on `NodeList` to convert js list to a dart list.
<details>
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart …
> [feat] Adds helpers to convert js lists to a dart list (Resolves #281)

- web/CHANGELOG.md
- web/lib/src/dom/css_animations.dart
- web/lib/src/dom/css_typed_om.dart
- web/lib/src/dom/dom.dart
- web/lib/src/dom/html.dart
- web/lib/src/dom/media_source.dart
- web/lib/src/dom/svg.dart
- web/test/smoke_test.dart
- web_generator/lib/src/translator.dart
Closes https://github.com/dart-lang/web/issues/127
The IDL defines unnamed getters or setters which should be emitted as special variants of the index operators.
> Add [] and []= operators for unnamed getters and setters

- web/CHANGELOG.md
- web/lib/src/helpers/extensions.dart
- web/test/helpers_test.dart
Move this extension from [`package:http`](https://github.com/dart-lang/http/blob/b97b8dc22ea808c4fbd63f73abd7af8ecf694323/pkgs/http/lib/src/browser_client.dart#L124) here, it might also be used in [`package:grpc`](https://github.com/grpc/grpc-dart/pull/730/files#r1722304772).
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package …
> Add `responseHeaders` extension on `XMLHttpRequest`

- web/CHANGELOG.md
- web/lib/src/dom/wasm_js_api.dart
- web_generator/CHANGELOG.md
- web_generator/lib/src/translator.dart
- web_generator/lib/src/webidl_api.dart
[feat] LegacyNamespace extended attributes support on IDL interfaces (Resolves #283)
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/blob/main/docs/External-Package-Maintenance.md#making-a-change).
- Changes to packages require [corresponding …
> [feat] LegacyNamespace extended attributes support on IDL interfaces (Resolves #283)

- web_generator/lib/src/dart_main.dart
- web_generator/lib/src/util.dart
- web_generator/pubspec.yaml
languageVersion will soon be a required parameter. For our purposes, it suffices to use the latest as it includes formatting for extension types. There are no changes in the generated output.
> Update dart_style and use latestLanguageVersion

- web/lib/src/dom/cssom.dart
- web/lib/src/dom/dom.dart
- web/lib/src/dom/gamepad.dart
- web/lib/src/dom/hr_time.dart
- web/lib/src/dom/html.dart
- web/lib/src/dom/mathml_core.dart
- web/lib/src/dom/permissions.dart
- web/lib/src/dom/service_workers.dart
- web/lib/src/dom/storage.dart
- web/lib/src/dom/svg.dart
- web/lib/src/dom/uievents.dart
- web/lib/src/dom/url.dart
- web/lib/src/dom/web_animations.dart
- web/lib/src/dom/webrtc.dart
- web/lib/src/dom/webxr.dart
- web_generator/lib/src/generate_bindings.dart
- web_generator/lib/src/translator.dart
Currently, the generator adds members to interfacelikes as we process various IDL files. This may lead to partial interfaces being added before the interface definition. Instead, this CL adds partials after the interface definition, and then applies mixins. It also dedups some logic around browser compatibility so that we only check compatibility and process in one location.
While there is a diff in the generated files, it is functionally the same because all we do is move members around in the same extension type.
> Refactor generation logic so partials come after

- web/lib/src/helpers/extensions.dart
Also update the spec reference to a functional, up-to-date location.
> Fix location of `responseHeaders` API doc

- web/CHANGELOG.md
- web/lib/src/helpers.dart
- web/lib/src/helpers/cross_origin.dart
- web/lib/src/helpers/extensions.dart
- web/test/helpers_test.dart
Closes https://github.com/dart-lang/sdk/issues/54443
Closes https://github.com/dart-lang/web/issues/247
Closes https://github.com/dart-lang/sdk/issues/54938
Since cross-origin objects have limitations around access, wrappers are introduced to do the only safe operations. Extension methods are added to get instances of these wrappers.
I'll work on getting a test in the SDK doing the interop operations with `JSAny?` so that ability we're relying on here won't regress and we can get better coverage.
> Add cross-origin window and location wrappers

- web/CHANGELOG.md
- web/pubspec.yaml
.
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/blob/main/docs/External-Package-Maintenance.md#making-a-change).
Note that many Dart repos have a weekly cadence for …
> Publish `package:web`

- web/analysis_options.yaml
- web_generator/analysis_options.yaml
Reference: https://github.com/dart-lang/linter/issues/5107
> Remove the deprecated `package_api_docs` lint

- .github/workflows/dart.yml
- tool/ci.sh
- web_generator/bin/update_bindings.dart
- web_generator/lib/src/dart_main.dart
- web_generator/mono_pkg.yaml
- web_generator/pubspec.yaml
Also wired through the language version of the target `web` package
> generator: Support the latest package dependencies

- web/CHANGELOG.md
- web/lib/src/helpers/events/events.dart
- web/pubspec.yaml
#330 
add `onLoad` event and [some other events shown on MDN](https://developer.mozilla.org/en-US/docs/Web/API/FileReader/load_event), such as `onLoadStart`, `onProgress` etc.
minor detail: fix the extension method name typo `FileReaderEventGEtters`
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package …
> Add missing FileReader event getters

- web/CHANGELOG.md
- web/lib/fix_data.yaml
- web/renames.md
- web/test_fixes/renames.dart
- web/test_fixes/renames.dart.expect
reference: #331 
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/blob/main/docs/External-Package-Maintenance.md#making-a-change).
Note that many Dart repos have a weekly …
> Remove renames where the type doesn't exist anymore

- web/CHANGELOG.md
- web/test/dart_fix_test.dart
- web_generator/CHANGELOG.md
- web_generator/bin/scrape_mdn.dart
- web_generator/bin/update_bindings.dart
related: #335 
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/blob/main/docs/External-Package-Maintenance.md#making-a-change).
Note that many Dart repos have a weekly …
> Adapt paths for different development environments

- web_generator/lib/src/banned_names.dart
Generating all the bindings generates codes with these keywords, leading to analysis errors. Members with this name will be renamed using `@JS`.
> Add catch and finally to bannedNames

- web_generator/bin/update_bindings.dart
- web_generator/pubspec.yaml
New version of analyzer requires a migration: https://github.com/dart-lang/sdk/blob/main/pkg/analyzer/doc/element_model_migration_guide.md. Makes Dart CI green again.
> Migrate web_generator to new element model

- web_generator/lib/src/cli.dart
- web_generator/lib/src/interop_gen/parser.dart
- web_generator/lib/src/js/node.dart
- web_generator/lib/src/js/typescript.dart
- web_generator/test/assets/invalid.d.ts
- web_generator/test/invalid_input_test.dart
Fixes #421 
This PR adds support for handling diagnostics and errors when parsing TS declaration files for the generator to transform, preventing the generator from handling invalid TS files. 
Diagnostics are printed in the following format
```log
<filename> (<line no>,<char no>): <message>
```
And the process exits with status code 1.
> [interop] Implement Diagnostics and Handling Errors

- web_generator/lib/src/ast/helpers.dart
- web_generator/lib/src/ast/types.dart
- web_generator/lib/src/interop_gen/transform/transformer.dart
- web_generator/lib/src/js/typescript.types.dart
- web_generator/test/integration/interop_gen/ts_typing_expected.dart
- web_generator/test/integration/interop_gen/ts_typing_input.d.ts
Fixes #464 
Fixes #463
This PR adds support for transforming conditional types (`t extends a ? b : c`) and predicate types (`t is a`), and generates Dart alternatives to these types.
Predicate types are converted to booleans, while conditional types are converted to unions, since the result can either be one or the other. There currently isn't a way (afaik) to introspect into parameter values to give a specific result depending on the parameter result.
We could be smart, however, and wrap such methods with other methods to do the casting for us in the case of conditional types, and could _try_ to do similar in predicate types (via `assert` checks and more).
> [interop] Add support for Conditional and Predicate Types
